version: '3.1'
services:
  elastic:
    image: badanin87/elastic_netology:v1.0
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/var/lib/elasticsearch
