Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "public_network"
  config.vm.provision :shell, path: "bootstrap.sh", env: {"VAULT_ADDR" => "http://127.0.0.1:8200"}
  config.vm.provider "virtualbox" do |v|
    v.name = "kurs_1"
  end
end
